services:
  frontend:
    image: ${FRONTEND_IMAGE_TAG}:latest
    ports:
      - "5173:5173"
  
  backend:
    image: ${BACKEND_IMAGE_TAG}:latest
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
